### ISSUE TITLE
[FIX] : 마지막에 !! 최종 에러 핸들링

### ISSUE THREAD

**Issue by yskim6772** [IT-Pick/IT-Pick-Frontend#123]
## 📌𝗧𝗮𝘀𝗸
- [ ] 전체적으로 에러 핸들링 및 오류 발견 후 수정
- [ ] 안 되는 부분 없나 확인

- [x] 랭킹 부분 h-screen 에서 h-full로 변경
- [ ] 홈 화면에서 커뮤니티 클릭시 해당 커뮤니티 랭킹으로 이동 
- [ ] 검색시 태그 없으면 간격 좁아지는 css 구현

### 선택사항
- [ ] 홈 화면에서 best3 항목- 제목 클릭해야 게시글로 이동됨, 사진 클릭해도 이동되면 좋겠음
- [x] 토론 글 ui 수정: 분전, 답글달기
![Screenshot 2024-08-20 at 5 50 35 AM](https://github.com/user-attachments/assets/dcd2c7eb-a7d5-46ff-be9c-0b3e339e57b4)

**Comment by clicelee** [comment]
closed
